### ISSUE TITLE
KeyError: 'unit_dim'

### ISSUE THREAD

**Issue by Isaac009** [zyh1999/CADP#1]
Hello author,

I got this error when I ran the code to replicate the results: 
marl_env/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Could not seed environment <FootballEnv instance>
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
[DEBUG 12:57:47] pymarl Stopping Heartbeat
[ERROR 12:57:47] pymarl Failed after 0:00:01!
Traceback (most recent call last):
  File "marl_env/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "marl_env/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "marl_env/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "marl_env/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "CADP/CADP-VD/src/main.py", line 35, in my_main
    run(_run, config, _log)
  File "MARL/CADP/CADP-VD/src/run.py", line 48, in run
    run_sequential(args=args, logger=logger)
  File "/home/jupyter-isack/Documents/PBCS/MASER/CADP/CADP-VD/src/run.py", line 86, in run_sequential
    args.unit_dim = env_info["unit_dim"]
KeyError: 'unit_dim'

The command I ran: `python3 CADP-VD/src/main.py --config=QMIX_CADP --env-config=gfootball with env_args.map_name=academy_3_vs_1_with_keeper optimizer='rmsprop'`

**Comment by zyh1999** [comment]
Thank you for your feedback. I indeed overlooked this issue. Please disregard the mentioned sentence  “File "/home/jupyter-isack/Documents/PBCS/MASER/CADP/CADP-VD/src/run.py", line 86, in run_sequential
args.unit_dim = env_info["unit_dim"]”
as it has been deleted. I have already updated the version, rectifying this bug.
